services:
  fenrir:
    image: fenrir
    container_name: fenrir
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
      # - "443:443"
    environment:
      TZ: "America/Sao_Paulo"
      FTLCONF_webserver_api_password: "root"
    volumes:
      - ./data/etc-pihole/:/etc/pihole/
      - ./data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
